#!/usr/bin/env php
<?

#Pull some default data
libxml_use_internal_errors(true); # Suppress any warnings from xml errors.
$scriptName = "DriveStandbyMonitor";
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';
$pluginRoot = "$docroot/plugins/$scriptName";
include_once( "./plugins/$scriptName/includes/page.php" );

$DSM = new DisksInfo( $disks );
$DB = new DSMDB( $DB_FILE );
$DB->logEntries( $DSM->getDisks() );

?>